### PR TITLE
Fix Typo

### PR DESCRIPTION
**Pull request by tim-win**
This demonstrate_s_ poor code organization.

### CODE REVIEW

**Comment by Tim-Clifford** [comment]
There are more. I think I give up though.

**Comment by trochette** [comment]
Thanks Tim! My first language is French, still need to improve my english grammar.

**Comment by tim-win** [comment]
If it's any consolation you're way better at Angular than I am, and the guise is great.

**Comment by tim-win** [comment]
Guide*

**Comment by petergeyer** [comment]
Hey. I can't run index and I just get an error 
XMLHttpRequest cannot load file:///C:/Users/christopher.ieng/Desktop/Angular-Design-Patterns-Best-Practices-master/mocks/slides.json. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

Say wot m8?!

**Comment by petergeyer** [comment]
I can't seem to run the index.html as I get this error:
XMLHttpRequest cannot load file:///C:/Users/username/Desktop/Angular-Design-Patterns-Best-Practices-master/mocks/slides.json. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

say w0t

**Pull request merged**
